server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/resultados/ {
        proxy_pass http://results-api:8080/api/;
    }

    location /api/ {
        proxy_pass http://betting-api:8080/api/;
    }

    location /payments/ {
    proxy_pass http://payments-api:8080/api/;
    proxy_set_header Host $host;
}
}